#!/usr/bin/env python3
"""Produce the small static font instances used by build.py.

Downloads the variable fonts (Source Serif 4 and Inter, both SIL OFL) from the
google/fonts repository, instantiates them at the weights and optical sizes the
cards use, and subsets them to the Latin glyphs the README
needs. The resulting files are committed under scripts/fonts/ so the daily
GitHub Action never has to touch the network for fonts.

Run only when the font set needs to change:  python scripts/prepare_fonts.py
"""
from __future__ import annotations

import io
import urllib.request
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

FONT_DIR = Path(__file__).resolve().parent / "fonts"

SOURCES = {
    "SourceSerif4": "https://github.com/google/fonts/raw/main/ofl/sourceserif4/SourceSerif4%5Bopsz%2Cwght%5D.ttf",
    "Inter": "https://github.com/google/fonts/raw/main/ofl/inter/Inter%5Bopsz%2Cwght%5D.ttf",
}

# (output name, source family, axis location): headings use Source Serif 4 at
# wght 540, eyebrows use Inter at wght 720.
INSTANCES = [
    ("SourceSerif4-Display", "SourceSerif4", {"wght": 540, "opsz": 60}),
    ("SourceSerif4-Text", "SourceSerif4", {"wght": 540, "opsz": 20}),
    ("SourceSerif4-TextRegular", "SourceSerif4", {"wght": 400, "opsz": 20}),
    ("Inter-Regular", "Inter", {"wght": 400, "opsz": 14}),
    ("Inter-Medium", "Inter", {"wght": 500, "opsz": 14}),
    ("Inter-Bold", "Inter", {"wght": 720, "opsz": 14}),
]

# Basic Latin, Latin-1 Supplement, general punctuation, plus the arrow used for
# external links. Anything outside this range falls back to .notdef at build
# time, so extend it here if profile.toml gains new characters.
UNICODES = (
    list(range(0x0020, 0x007F))
    + list(range(0x00A0, 0x0100))
    + [0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x2197]
)


def download(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "ArcueidMP-profile-fonts"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def main() -> None:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    variable: dict[str, bytes] = {}
    for family, url in SOURCES.items():
        print(f"downloading {family} ...")
        variable[family] = download(url)

    options = subset.Options()
    options.layout_features = ["kern", "liga", "calt", "mark", "mkmk"]
    options.name_IDs = ["*"]
    options.notdef_outline = True
    options.recalc_bounds = True
    options.drop_tables += ["DSIG"]

    for name, family, location in INSTANCES:
        font = TTFont(io.BytesIO(variable[family]))
        static = instancer.instantiateVariableFont(font, location, inplace=False)
        subsetter = subset.Subsetter(options)
        subsetter.populate(unicodes=UNICODES)
        subsetter.subset(static)
        out = FONT_DIR / f"{name}.ttf"
        static.save(out)
        print(f"  {out.name:32s} {out.stat().st_size / 1024:6.1f} KB  {location}")

    (FONT_DIR / "LICENSE.md").write_text(
        "Source Serif 4 (c) Adobe Systems Incorporated and Inter (c) The Inter Project Authors.\n"
        "Both fonts are licensed under the SIL Open Font License 1.1 and are redistributed here\n"
        "as static, subsetted instances generated by scripts/prepare_fonts.py.\n"
        "https://openfontlicense.org/\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
